// frontend-admin/src/pages/Login.jsx
import { useState } from 'react'
import { Card, Input, Button, message } from 'antd'
import request from '../api/request'

export default function Login() {
  const [form, setForm] = useState({ username: '', password: '' })

  const handleLogin = async () => {
    try {
      const { data } = await request.post('/auth/login', form)
      localStorage.setItem('token', data.token)
      message.success('登录成功')
      window.location.href = '/'
    } catch (e) {
      message.error('登录失败')
    }
  }

  return (
    <div style={{ display: 'flex', justifyContent: 'center', padding: 80 }}>
      <Card title="管理员登录" style={{ width: 320 }}>
        <Input
          placeholder="用户名"
          value={form.username}
          onChange={(e) => setForm({ ...form, username: e.target.value })}
          style={{ marginBottom: 12 }}
        />
        <Input.Password
          placeholder="密码"
          value={form.password}
          onChange={(e) => setForm({ ...form, password: e.target.value })}
          style={{ marginBottom: 12 }}
        />
        <Button type="primary" block onClick={handleLogin}>登录</Button>
      </Card>
    </div>
  )
}

// frontend-store/src/views/Login.vue
<template>
  <div class="login">
    <el-card class="box">
      <h2>登录</h2>
      <el-input v-model="form.username" placeholder="用户名" style="margin-bottom: 12px;" />
      <el-input v-model="form.password" type="password" placeholder="密码" style="margin-bottom: 12px;" />
      <el-button type="primary" @click="handleLogin">登录</el-button>
    </el-card>
  </div>
</template>

<script setup>
import { reactive } from 'vue'
import { ElMessage } from 'element-plus'
import { login } from '../api/auth'

const form = reactive({ username: '', password: '' })

const handleLogin = async () => {
  try {
    const { data } = await login(form)
    localStorage.setItem('token', data.token)
    ElMessage.success('登录成功')
    location.href = '/'
  } catch (e) {
    ElMessage.error('登录失败')
  }
}
</script>

<style>
.login { display: flex; justify-content: center; padding: 80px; }
.box { width: 320px; }
</style>
